### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix

### ISSUE THREAD

**Issue by bhhsieh** [clovaai/donut#214]
Hi,
I ran donut a month ago and it was fine.
But when I run it today, it shows the following error message.
"RuntimeError: CUDA error: CUBLAS_STATUS_NOT_SUPPORTED when calling `cublasGemmStridedBatchedExFix( handle, opa, opb, m, n, k, (void*)(&falpha), a, CUDA_R_16F, lda, stridea, b, CUDA_R_16F, ldb, strideb, (void*)(&fbeta), c, CUDA_R_16F, ldc, stridec, num_batches, CUDA_R_32F, CUBLAS_GEMM_DEFAULT_TENSOR_OP)`"

The script is exactly same as before.
Does this related to recent updates in key dependency libraries?
How could I solve this error?

**Comment by bhhsieh** [comment]
I solved it by simply `pip uninstall nvidia-cublas-cu11`
not sure whether it is the correct way 

Reference: https://discuss.pytorch.org/t/runtimeerror-cuda-error-cublas-status-invalid-value-when-calling-cublassgemm-handle-opa-opb-m-n-k-alpha-a-lda-b-ldb-beta-c-ldc/124544/22
